### ISSUE TITLE
rtRemote: search needs to be faster

### ISSUE THREAD

**Issue by gladish** [pxscene/pxCore#117]
Search protocol should retry very quickly with some type of back-off. Parameter(s) should be configurable.

**Comment by vertexodessa** [comment]
I think this is fixed by 
https://github.com/johnrobinsn/pxCore/pull/151
and
 (yet unmerged) https://github.com/johnrobinsn/pxCore/pull/154

**Comment by conniefry** [comment]
Closing. If this is still an issue, please create new issue in the pxscene/rtRemote repository.
