### ISSUE TITLE
rtRemote: need abstraction for endpoints

### ISSUE THREAD

**Issue by gladish** [pxscene/pxCore#118]
In order to cleanly support communication over various transports, we need to abstract what it is that we use for an endpoint. Right now, the code uses sockaddr_storage to support ipv4/v6, but for non IP transports, other endpoint types will be needed. WebPA, Shared Memory, etc.

We should have factory function to create rtRemoteEndpoint. We can specific string as type switcher. i.e.

`std::string s = "tcp://192.168.1.1:1234";`
`rtRemoteEndpoint* e = rtRemoteEndpointCreate(env, s);`

We'll also want a public API where users can register new endpoint implementations.

`std::string scheme = "webpa";`
`rtRemoteEndpointRegister(scheme, my_factory_function);`

then later
`rtRemoteEndpoint* e = rtRemoteEndpointCreate(env, 'webpa://192.168.101.');`

**Comment by conniefry** [comment]
Closing. If this is still an issue, please create new issue in the pxscene/rtRemote repository.
