### ISSUE TITLE
rtRemote: Event  callback unregistration with rtRemote

### ISSUE THREAD

**Issue by gladish** [pxscene/pxCore#132]
Hi Jacob,

Today, when we try to add and remove event listeners with rtRemote, event unregistrations are not happening. Attached is  the client,server code, which is being tried.

For every event registered, event name and function address are stored as rtEmit entry in server side. For add/delete request, we are passing two parameters name and rtFunctionRef from client side. When the parameters are parsed in server side, a new rtRemoteFunction object is created in heap for rtFunctionRef parameter. These two generated rtFunctionRef addresses are compared during event deletion, which is failing (as they are two different heap addresses).

rtError
rtValueReader::read(rtValue& to, rapidjson::Value const& from, std::shared_ptr<rtRemoteClient> const& client)
{
..............
case RT_functionType:
to.setFunction(new rtRemoteFunction(objectId, functionId, client)); //This is created two times during event addition and deletion. Somehow, this needs to get the old rtRemotefunction address got during event addition and use it for comparision in rtEmit entry during unregistration.

Are we missing anything?. Please provide your suggestions.

Thanks.

Regards,
Madan

**Comment by gladish** [comment]
[rtevent.txt](https://github.com/johnrobinsn/pxCore/files/418648/rtevent.txt)

**Comment by conniefry** [comment]
A similar issue was fixed for pxCore events in [PR 1149]( https://github.com/pxscene/pxCore/pull/1149).  

Closing.  If this is still an issue for rtRemote, please create new issue in [pxscene/rtRemote ](https://github.com/pxscene/rtRemote)repository.
