### ISSUE TITLE
Make spin timeouts configurable with rtRemoteConfig

### ISSUE THREAD

**Issue by vertexodessa** [pxscene/pxCore#152]
In rtRemoteMulticastResolver::sendSearchAndWait two spin timeouts are hardcoded:
- starting spin timeout (currently hardcoded to 30ms)
- spin iteration increase time (currently hardcoded to 20 ms)

It would be nice to make them configurable.

**Comment by vertexodessa** [comment]
created a pull request: https://github.com/johnrobinsn/pxCore/pull/154

**Comment by conniefry** [comment]
Closing.  If this is still an issue, please create an issue in the [pxscene/rtRemote repository](https://github.com/pxscene/rtRemote).
