### ISSUE TITLE
rtRemote strips the last symbol of config file

### ISSUE THREAD

**Issue by vertexodessa** [pxscene/pxCore#167]
If the config file ends with a new line, it's ok.
But if config file does not end with new line, last symbol will be cut off.

**Comment by manuduggal** [comment]
I am not seeing this issue. I checked it by modifying the rtremote.conf by adding another line ( did newline or enter on last line) , adding another property ( with proper syntax ) and did not enter "newline" or "carriage return" on the last line . On startup of "./rpcSampleApp"  , it parses all the information from "rtremote.conf" properly .

**Comment by conniefry** [comment]
Closing.  If this is still an issue, please create an issue in the [pxscene/rtRemote repository](https://github.com/pxscene/rtRemote).
