### ISSUE TITLE
build on windows

### ISSUE THREAD

**Issue by Muneem** [pxscene/pxCore#243]
How to build it in windows?

**Comment by cfry002** [comment]
The windows build is stale right now, but we will be reviving it shortly.

**Comment by Muneem** [comment]
when its reviving? Any expected date?

**Comment by johnrobinsn** [comment]
Some folks are picking at it... But no specific eta yet...  check back in 3-4 months

**Comment by conniefry** [comment]
Windows is now supported.  Please see the Readme in pxCore/examples/pxScene2d, and give it a try.

**Comment by conniefry** [comment]
There is also a Windows binary now published on pxscene.org.
