### ISSUE TITLE
Build pxscene failing

### ISSUE THREAD

**Issue by nkg77** [pxscene/pxCore#496]
build system: Ubuntu 14.04

pxWindowNative.cpp:(.text+0xf00): undefined reference to `glutRemapKeys'
collect2: error: ld returned 1 exit status
make: *** [pxscene] Error 1

**Comment by conniefry** [comment]
Please give details of your build steps.  Are you following the instructions for Ubuntu builds from this readme? https://github.com/pxscene/pxCore/blob/master/examples/pxScene2d/README.md

**Comment by nkg77** [comment]
Yes I was following the instructions for Ubuntu in the readme.Sent from my phoneOn 25-Jul-2017 22:40, conniefry <notifications@github.com> wrote:Please give details of your build steps.  Are you following the instructions for Ubuntu builds from this readme? https://github.com/pxscene/pxCore/blob/master/examples/pxScene2d/README.md

**Comment by conniefry** [comment]
Are you using USE_EXTERNALS_GLUT?  I suggest trying without if you don't have a particular need for it.

**Comment by nkg77** [comment]
Was able to get it working without using USE_EXTERNALS_GLUT. Thanks for the suggestion.
