### ISSUE TITLE
pxCore not working with wayland_egl rendering...!!

### ISSUE THREAD

**Issue by karora123** [pxscene/pxCore#518]
Is the pxCore with wayland working? 
I compile pxCore library using Makefile.wayland_egl.....made few changes required to generate object and archive files.
In my case, I am not able to display/render the pictures given through the URL. Is there anything I missed out??

It works fine with pxCore enabled EGL rendering..!!

**Comment by andrewbenton** [comment]
What platform are you running this on?

**Comment by mfiess** [comment]
pxCore with wayland egl support is now available using cmake.  Updates to the documentation will be available shortly.

**Comment by conniefry** [comment]
Fixed in PR #519.

**Comment by karora123** [comment]
Yes, its working now as per changes of wayland updates #519 . In addition to that modify Makefile & provide display server to wayland API worked for me.
