### ISSUE TITLE
pxWayland.cpp:142:87: error: invalid conversion (void * <-> uint32_t)

### ISSUE THREAD

**Issue by dwrobel** [pxscene/pxCore#668]
pxCore/examples/pxScene2d/src/pxWayland.cpp:142:87: error: invalid conversion from ‘void (*)(WstCompositor*, void*, void*) {aka void (*)(_WstCompositor*, void*, void*)}’ to ‘WstDecodeHandlerCallback {aka void (*)(_WstCompositor*, void*, unsigned int)}’ [-Werror=permissive]
       if ( !WstCompositorSetDecoderHandleCallback( mWCtx, decoderHandleCallback, this ) )
                                                                                       ^
pxSceen uses:
static void decoderHandleCallback( WstCompositor *wctx, void *userData, void* decoderHandle);

while https://github.com/rdkcmf/westeros/blob/master/westeros-compositor.h#L59 declares callback type as:

typedef void (*WstDecodeHandlerCallback)( WstCompositor *ctx, void *userData, uint32_t decoderHandle);

which means that, in practice the Westeros API doesn't allow you to pass any pointer through the decoderHandle parameter (it's not portable and also will not work on 64-bit platforms).

**Comment by mfiess** [comment]
This is now fixed by pull request 710.
