### ISSUE TITLE
rtRpcInit() fails to initialize a rtRpcServer object if called more than once

### ISSUE THREAD

**Issue by goruklu** [pxscene/pxCore#84]
When rtRpcInit() is called a second time (after a rtRpcShutdown() call), gServer is not being initialized and the following rtRpcRegisterObject() fails due to gServer being NULL.

Here is the relevant code in rtRpc.cpp:

```
  std::call_once(gServerOnce, [&e]()
  {
    gServer = new rtRpcServer();
    e = gServer->open();
    if (e != RT_OK)
    {
      rtLogError("failed to open rtRpcServer. %s", rtStrError(e));
    }
  });
```

Looking at the code this seems to be by design since std::call_once is being used but I don't know how we can then use rtRPC calls in a situation where we need to shutdown and initialize the RPC module more than once.

Can we just do the following instead ?

```
  if(gServer == nullptr)
  {
    gServer = new rtRpcServer();
    e = gServer->open();
    if (e != RT_OK)
    {
      rtLogError("failed to open rtRpcServer. %s", rtStrError(e));
    }
  }
```

**Comment by conniefry** [comment]
Closing.  If this is still an issue, please create new issue in the [pxscene/rtRemote](https://github.com/pxscene/rtRemote) repository.
